APP/NC.MVC/Areas/ad_min/Controllers/SettingsController.cs
using System;
using System.Data;
using System.Text;
using Microsoft.AspNetCore.Mvc;

using NC.Common;
using NC.Core;
using NC.Model.Models;
using NC.Lib;
using NC.Model;

namespace NC.MVC.Areas.ad_min.Controllers
{
    [Area(AreaNames.Admin)]
    public class SettingsController : AdminBase
    {
        public SettingsController(NCMVC_DBContext _dblEf) : base(_dblEf)
        {
        }

        private string action = JHEnums.ActionEnum.Add.ToString(); //操作类型
        protected string strStatus = string.Empty;
        protected string strMsg = string.Empty;
        #region --系统设置--
        [NavAttr(NavName = "site_config", ActionType = "View")]
        public IActionResult Sys_Config()
        {
            return View(siteConf);
        }

        /// <summary>
        /// 保存配置文件
        /// </summary>
        /// <param name="model"></param>
        [NavAttr(NavName = "site_config", ActionType = "Edit")]
        public JsonResult SysConfigSave()
        {
            siteconfig model = configSite.loadConfig();
            try
            {
                model.IsEmail = Utils.StrToInt(Request.Form["rblEmail"], 0);
                model.webname = Request.Form["webname"];
                model.weburl = Request.Form["weburl"];
                model.weblogo = Request.Form["weblogo"];
                model.webcompany = Request.Form["webcompany"];
                model.webaddress = Request.Form["webaddress"];
                model.webtel = Request.Form["webtel"];
                model.webfax = Request.Form["webfax"];
                model.webmail = Request.Form["webmail"];
                model.webcrod = Request.Form["webcrod"];
                model.webtitle = Request.Form["webtitle"];
                model.webkeyword = Request.Form["webkeyword"];
                model.webdescription = Utils.DropHTML(Request.Form["webdescription"]);
                model.webcopyright = Request.Form["webcopyright"];

                model.webpath = Request.Form["webpath"];
                model.webmanagepath = Request.Form["webmanagepath"];
                model.staticstatus = Utils.StrToInt(Request.Form["staticstatus"], 0);
                model.staticextension = Request.Form["staticextension"];

                model.memberstatus = !string.IsNullOrEmpty(Request.Form["memberstatus"]) ? 1 : 0;
                model.commentstatus = !string.IsNullOrEmpty(Request.Form["commentstatus"]) ? 1 : 0;
                model.logstatus = !string.IsNullOrEmpty(Request.Form["logstatus"]) ? 1 : 0;
                model.webstatus = !string.IsNullOrEmpty(Request.Form["webstatus"]) ? 1 : 0;

                model.webclosereason = Request.Form["webclosereason"];
                model.webcountcode = Request.Form["webcountcode"];

                model.smsusername = Request.Form["smsusername"];
                string defaultpassword = "0|0|0|0"; //默认显示密码
                //判断密码是否更改
                if (Request.Form["smspassword"].ToString() != "" && Request.Form["smspassword"].ToString() != defaultpassword)
                {
                    model.smspassword = MD5Comm.Get32MD5One(Request.Form["smspassword"].ToString());
                }

                model.emailsmtp = Request.Form["emailsmtp"];
                model.emailport = Utils.StrToInt(Request.Form["emailport"].ToString(), 25);
                model.emailfrom = Request.Form["emailfrom"];
                model.emailusername = Request.Form["emailusername"];
                //判断密码是否更改
                if (Request.Form["emailpassword"] != defaultpassword)
                {
                    model.emailpassword = DESEncrypt.Encrypt(Request.Form["emailpassword"], model.sysencryptstring);
                }
                model.emailnickname = Request.Form["emailnickname"];

                model.filepath = Request.Form["filepath"];
                model.filesave = Utils.StrToInt(Request.Form["filesave"], 2);
                model.fileextension = Request.Form["fileextension"];
                model.attachsize = Utils.StrToInt(Request.Form["attachsize"], 0);
                model.imgsize = Utils.StrToInt(Request.Form["imgsize"], 0);
                model.imgmaxheight = Utils.StrToInt(Request.Form["imgmaxheight"], 0);
                model.imgmaxwidth = Utils.StrToInt(Request.Form["imgmaxwidth"], 0);
                model.thumbnailheight = Utils.StrToInt(Request.Form["thumbnailheight"], 0);
                model.thumbnailwidth = Utils.StrToInt(Request.Form["thumbnailwidth"], 0);
                model.watermarktype = Utils.StrToInt(Request.Form["watermarktype"], 0);
                model.watermarkposition = Utils.StrToInt(Request.Form["watermarkposition"], 9);
                model.watermarkimgquality = Utils.StrToInt(Request.Form["watermarkimgquality"], 80);
                model.watermarkpic = Request.Form["watermarkpic"];
                model.watermarktransparency = Utils.StrToInt(Request.Form["watermarktransparency"], 5);
                model.watermarktext = Request.Form["watermarktext"];
                model.watermarkfont = Request.Form["watermarkfont"];
                model.watermarkfontsize = Utils.StrToInt(Request.Form["watermarkfontsize"], 12);

                configSite.saveConifg(model);
                strStatus = "1";
                strMsg = "修改系统配置成功";
            }
            catch
            {
                strStatus = "0";
                strMsg = "文件写入失败，请检查是否有权限！";
            }
            return Json(new { status = strStatus, msg = strMsg });
        }
        #endregion

        #region --基础字典列表--
        /// <summary>
        /// 字典列表
        /// </summary>
        [NavAttr(NavName = "sys_dictbase")]
        public ActionResult DictBase_List()
        {
            string keyword = Request.Query["keyword"];//搜索关键字
            ViewBag.keyword = keyword;
            return View();
        }
        /// <summary>
        /// 基础字典列表
        /// </summary>
        [HttpPost]
        [NavAttr(NavName = "sys_dictbase")]
        public string DictBase_Bind()
        {
            int pageSize = Utils.StrToInt(Request.Query["page_size"]);
            int pageIndex = Utils.StrToInt(Request.Query["page_index"], 0) + 1;
            string keyword = Request.Query["keyword"];//搜索关键字
            string strWhere = string.Empty;
            if (!string.IsNullOrEmpty(keyword))
            {
                strWhere += " and (Key_Type like  '%" + keyword + "%' or Key_Value like '%" + keyword + "%')";
            }
            string filedOrder = " id Desc,Sort_ID asc";
            string fields = " id , Key_Type , Key_Code , Key_Value , Code_Value , Sort_ID , OStatus  ";

            DbParameters p = new DbParameters();
            p.Add("@Tables", "nc_dictbase");
            p.Add("@PrimaryKey", "id");
            p.Add("@Fields", fields);
            p.Add("@Filter", strWhere);
            p.Add("@Sort", filedOrder);
            p.Add("@PageSize", pageSize);
            p.Add("@CurrentPage", pageIndex);
            p.AddOut("@TotalCount", "int", 4);

            DataTable dt = Dbl.ZZCMS.CreateDataTable("Pr_PageView", p);
            int recordCount = Utils.StrToInt(p[p.Length - 1].Value.ToString(), 0);
            //objecttojson转，不可以直接rows=dt会转成xml格式
            //JsonHelper.ObjectToJSON(new { rows = JsonHelper.DataTableToJSON(dt), total = recordCount });
            string result = "{\"rows\":" + JsonHelper.DataTableToJSON(dt) + ",\"total\":" + recordCount + "}";
            return result;
        }
        /// <summary>
        /// 删除字典
        /// </summary>
        [HttpPost]
        [NavAttr(NavName = "sys_dictbase")]
        public JsonResult DictBase_Del(string ids)
        {
            bool res = true;
            if (string.IsNullOrEmpty(ids))
            {
                res = false;
                strMsg = "删除参数异常！";//
            }
            else
            {
                string[] arrId = ids.Split(',');
                string result = string.Empty;
                try
                {
                    for (int i = 0; i < arrId.Length; i++)
                    {
                        int id = Utils.StrToInt(arrId[i]);
                        NcDictbase model = dblEf.Find<NcDictbase>(id);
                        if (model != null)
                        {
                            //dblEf.NcDictbase.Remove(m => m.id);//.Delete<NcDictbase>(m => m.id == id);//删除,linq to entities不识别xx[index]这种格式，需要先赋值临时变量
                            dblEf.Remove<NcDictbase>(model);
                            dblEf.SaveChanges();
                            res = true;
                            strMsg = "删除成功！";
                        }
                    }
                }
                catch (Exception ex)//循环删除，异常才报删除错误
                {
                    res = false;
                    strMsg = "删除过程中出现异常！";//调试过程中+ex.ToString();
                }
            }
            return Json(new { status = (res ? 1 : 0), message = strMsg });
        }

        /// <summary>
        /// 字典-编辑
        /// </summary>
        [NavAttr(NavName = "sys_dictbase")]
        public ActionResult DictBase_Edit()
        {
            action = Request.Query["act"];
            int id = Utils.StrToInt(Request.Query["id"]);
            NcDictbase model = new NcDictbase();
            if (action.ToLower() == JHEnums.ActionEnum.Edit.ToString().ToLower() && id != 0) //修改
            {
                model = dblEf.Find<NcDictbase>(id);
            }
            else
            {
                model.SortId = 1;
            }
            ViewBag.action = action;
            ViewBag.id = id;
            return View(model);
        }
        /// <summary>
        /// 字典保存方法
        /// </summary>
        /// <returns></returns>
        [NavAttr(NavName = "sys_dictbase")]
        public JsonResult DictBaseSave()
        {
            NcDictbase model = new NcDictbase();
            action = Request.Form["act"];

APP/NC.MVC/Areas/ad_min/Views/Settings/CreateJson.cshtml
@{
    /*
    *说明：生成JSON数据
    *作者：wyd 2016-12-16
    *修改：
    *备注：/admin/manager/createjson
    */
}
@{
    ViewBag.Title = "生成JSON数据";
    Layout = "~/Areas/ad_min/Views/Shared/_Layout.Edit.cshtml";
}
@using System.Data;
@using NC.Common;
@using NC.Core;
@using NC.Model.Models;
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-xs-9">
            @using (Html.BeginForm("CreateJsonSave", "Settings", FormMethod.Post, new { id = "mainForm", @class = "form-horizontal" }))
            {
                <div class="tab-content">
                    <dl>
                        <dt>SQL 语句：</dt>
                        <dd>
                            <textarea name="txtSql" class="input normal" rows="2" cols="20" id="txtSql" style="height:48px;width:636px;"></textarea>
                        </dd>
                    </dl>
                    <dl>
                        <dt>DSN 名称：</dt>
                        <dd><input name="txtDsn" class="input normal" type="text" value="NC" id="txtDsn" style="width:106px;" /></dd>
                    </dl>
                    <dl>
                        <dt>JSON 名称：</dt>
                        <dd><input name="txtName" class="input normal" type="text" id="txtName" /></dd>
                    </dl>
                    <dl>
                        <dt>生成结果：</dt>
                        <dd>
                            <textarea name="txtJSON" class="input normal" rows="2" cols="20" id="txtJSON" style="height: 286px; width: 636px;"></textarea>
                        </dd>
                    </dl>
                    <dl>
                        <dt></dt>
                        <dd>
                            <button class="btn btn-info" type="submit" id="btnSubmit">
                                <i class="fa fa-check bigger-110"></i>
                                生成JSON数据
                            </button>
                            <button class="btn btn-danger" type="button" id="btnCate" style="display:none;">
                                <i class="fa fa-check bigger-110"></i>
                                生成分类JSON
                            </button>
                            &nbsp; &nbsp; &nbsp;
                            <button class="btn" type="button" onclick="javascript:history.back(-1);">
                                <i class="fa fa-reply bigger-110"></i>
                                返回上一页
                            </button>
                            <div id="msgtips"></div>
                        </dd>
                    </dl>
                </div>


            }
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->

@section includeJs{
    <script type="text/javascript">
    $(function () {
        //form提交,生成JSON
        $saveForm =function () {
            $.ajaxPostJson("@Url.Action("CreateJsonSave", "Settings", new { Area = "ad_min" })", $("#mainForm").serialize(), function (result) {
                if (result.status > 0) {
                    $("#txtJSON").html(result.msg);
                    $("#btnSubmit").attr("disabled", false);
                    $("#msgtips").hide();
                } else {
                    $alert("生成失败！");
                    $("#btnSubmit").attr("disabled", false);
                    $("#msgtips").hide();
                }
            }, function (result) {
                $alert("生成异常！");
                $("#btnSubmit").attr("disabled", false);
                $("#msgtips").hide();
            }, function (XMLHttpRequest) {
                $("#btnSubmit").attr("disabled", true);
                $("#msgtips").show();
                $("#msgtips").css('background', 'url("/ad_min/skin/default/icon_onload.gif") no-repeat 0 5px');
                $("#msgtips").text("正在生成，请稍候...");
            });
            return false;
        };
        //初始化表单验证
        $("#mainForm").initValidform1($saveForm);
        //form提交,生成JSON
        $("#btnCate").click(function () {
            $.ajaxPostJson("@Url.Action("CreateCateJsonSave", "Settings", new { Area = "ad_min" })", $("#mainForm").serialize(), function (result) {
                if (result.status > 0) {
                    $("#txtJSON").html(result.msg);
                    $("#btnSubmit").attr("disabled", false);
                    $("#msgtips").hide();
                } else {
                    $alert("生成失败！");
                    $("#btnSubmit").attr("disabled", false);
                    $("#msgtips").hide();
                }
            }, function (result) {
                $alert("生成异常！");
                $("#btnSubmit").attr("disabled", false);
                $("#msgtips").hide();
            }, function (XMLHttpRequest) {
                $("#btnSubmit").attr("disabled", true);
                $("#msgtips").show();
                $("#msgtips").css('background', 'url("/ad_min/skin/default/icon_onload.gif") no-repeat 0 5px');
                $("#msgtips").text("正在生成，请稍候...");
            });

        });
    });
    </script>
}

APP/NC.MVC/Areas/ad_min/Views/Settings/DataBackUp.cshtml
@{
    /*
    *说明：数据库备份
    *作者：wyd 2016-11-30
    *修改：
    *备注：/admin/manager/databackup
    */
}
@{
    ViewBag.Title = "数据库备份";
    Layout = "~/Areas/ad_min/Views/Shared/_Layout.cshtml";
}
@using System.Data;
@using NC.Common;
@using NC.Core;
<!--如果做跨服务器备份，可以考虑把备份路径存入数据库，恢复时从数据库中拿bak路径;数据库备份,应用程序必须与数据库在同一服务器-->
<div class="main-content">
    <div class="page-content">
        <div class="page-header">
            <div class="toolbar">
                <div class="l-list">
                    <ul class="icon-list">
                        <li><a id="btnSave" class="save" href="javascript:;"><i class="fa fa-save"></i><span>备份数据库</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.page-header -->

        <table class="table table-striped table-bordered table-hover ltable">
            <thead>
                <tr>
                    <th width="20%" align="left">
                        文件名称
                    </th>
                    <th width="15%">
                        备份时间
                    </th>
                    <th width="12%">
                        操作
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow dr in ViewBag.DBack.Rows)
                {
                    <tr>
                        <td>@dr["filename"]</td>
                        <td>@dr["createdate"]</td>
                        <td><a href="javascript:;" class="restfile" data-attr="@dr["filename"]">恢复备份</a> | <a href="javascript:;');" class="dbackdel" data-attr="@dr["filename"]">删除备份</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section includeJs{
    <script type="text/javascript">
    $(function () {
        //保存
        $("#btnSave").click(function () {
            $.ajaxGetJson("@Url.Action("Backfile", "Settings", new { Area = "ad_min" })", "", function (result) {
                var url = "databackup";
                delAlert(result.msg, url);
                $("#btnSave").attr("disabled", false);
            }
            , function () { }
            , function (XMLHttpRequest) {//beforeSend
                $("#btnSave").attr("disabled", true);
                $("#btnSave").css({ "color": "red" });
            });

        });

        //恢复备份
        $(".restfile").click(function () {
            var fname = $(this).attr("data-attr");
            $confirm("为了您系统的安全！请尽量进入服务器手动进行恢复！", function () {
                $.ajaxGetJson("@Url.Action("Restfile", "Settings", new { Area = "ad_min" })", { fname: fname }, function (result) {
                    var url = "databackup";
                    delAlert(result.msg, url);
                }
                , function () { }
                , function (XMLHttpRequest) {//beforeSend
                    $(".restfile").attr("disabled", true);
                });

            })
        });
        //删除备份
        $(".dbackdel").click(function () {
            var fname = $(this).attr("data-attr");
            $confirm("确定删除？", function () {
                $.ajaxGetJson("@Url.Action("DbackDel", "Settings", new { Area = "ad_min" })", { fname: fname }, function (result) {
                    var url = "databackup";
                    delAlert(result.msg, url);
                }
                , function () { }
                , function (XMLHttpRequest) {//beforeSend
                    $(".dbackdel").attr("disabled", true);
                });

            })
        });

    });
    </script>
}

APP/NC.MVC/Areas/ad_min/Views/Settings/DictBase_Edit.cshtml
@{
    /*
    *说明：字典编辑
    *作者：wyd 2016-12-16
    *修改：
    *备注：/admin/manager/dictbase_edit
    */
}
@{
    ViewBag.Title = "字典编辑";
    Layout = "~/Areas/ad_min/Views/Shared/_Layout.Edit.cshtml";
}
@using System.Data;
@using NC.Common;
@using NC.Core;
@using NC.Model.Models;
@model NcDictbase
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-xs-9">
            @using (Html.BeginForm("DictBaseSave", "Settings", FormMethod.Post, new { id = "mainForm", @class = "form-horizontal" }))
            {
                <input type="hidden" name="act" value="@ViewBag.action" />
                <input type="hidden" name="id" value="@ViewBag.id" />

                <div class="tab-content">
                    <dl>
                        <dt>共通数据类别</dt>
                        <dd><input name="txtKey_Type" type="text" value="@Model.KeyType" id="txtKey_Type" class="input normal" /> <span class="Validform_checktip">*全部小写</span></dd>
                    </dl>
                    <dl>
                        <dt>项目代码</dt>
                        <dd><input name="txtKey_Code" type="text" value="@Model.KeyCode" id="txtKey_Code" class="input normal" /> <span class="Validform_checktip">*与共同类别形成唯一键</span></dd>
                    </dl>
                    <dl>
                        <dt>项目名称</dt>
                        <dd><input name="txtKey_Value" type="text" value="@Model.KeyValue" id="txtKey_Value" class="input normal" /> <span class="Validform_checktip">*</span></dd>
                    </dl>
                    <dl>
                        <dt>排序数字</dt>
                        <dd>
                            <input name="txtSortId" type="text" value="@Model.SortId" id="txtSortId" class="input t120" datatype="n" sucmsg=" " />
                            <span class="Validform_checktip">*数字，越小越向前</span>
                        </dd>
                    </dl>
                    <dl>
                        <dt></dt>
                        <dd>
                            <button class="btn btn-info" type="submit" id="btnSubmit">
                                <i class="fa fa-check bigger-110"></i>
                                提交保存
                            </button>
                            &nbsp; &nbsp; &nbsp;
                            <button class="btn" type="button" onclick="javascript:history.back(-1);">
                                <i class="fa fa-reply bigger-110"></i>
                                返回上一页
                            </button>
                            <div id="msgtips"></div>
                        </dd>
                    </dl>
                </div>

            }
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
@section includeJs{
    <script type="text/javascript">
    $(function () {
        //form提交
        $saveForm =function () {
            //alert($("#mainForm").serialize());
            //return false;
            $.ajaxPostJson("@Url.Action("DictBaseSave", "Settings", new { Area = "ad_min" })", $("#mainForm").serialize(), function (result) {
                if (result.status > 0) {
                    $confirm("保存成功，是否继续添加！", function () {
                        $("#btnSubmit").attr("disabled", false);
                        $("#msgtips").hide();
                    }, function () {
                        var url = "DictBase_List";
                        self.location = url;
                    });
                } else {
                    $alert("保存失败！");
                    $("#btnSubmit").attr("disabled", false);
                    $("#msgtips").hide();
                }
            }, function (result) {
                $alert("保存异常！");
                $("#btnSubmit").attr("disabled", false);
                $("#msgtips").hide();
            }, function (XMLHttpRequest) {
                $("#btnSubmit").attr("disabled", true);
                $("#msgtips").show();
                $("#msgtips").css('background', 'url("/ad_min/skin/default/icon_onload.gif") no-repeat 0 5px');
                $("#msgtips").text("正在保存，请稍候...");
            });
            return false;
        };
        //初始化表单验证
        $("#mainForm").initValidform1($saveForm);
    });
    </script>
}

APP/NC.MVC/Areas/ad_min/Views/Settings/DictBase_List.cshtml
@{
    /*
    *说明：基础字典列表
    *作者：wyd 2016-12-16
    *修改：
    *备注：/admin/manager/manager_log
    */
}
@{
    ViewBag.Title = "基础字典列表";
    Layout = "~/Areas/ad_min/Views/Shared/_Layout.cshtml";
}
@using System.Data;
@using NC.Common;
@using NC.Core;
<div class="main-content">
  
    <div class="page-content">
        <div class="page-header">
            <div class="toolbar">
                <div class="l-list">
                    <ul class="icon-list">
                        <li><a href="dictbase_edit?act=@JHEnums.ActionEnum.Add"><i class="fa fa-pencil-square-o"></i><span>新增</span></a></li>
                        <li><a class="all" href="javascript:;" onclick="checkAll(this);"><i class="fa fa-check-square-o"></i><span>全选</span></a></li>
                        <li><a id="btnDelete" class="del" href="javascript:;"><i class="fa fa-trash"></i><span>删除</span></a></li>
                    </ul>
                </div>
                <div class="r-list">
                    <input name="txtKeywords" type="text" id="txtKeywords" class="keyword" placeholder="请输入用户名" value="@ViewBag.keyword" />
                    <button id="btnSearch" class="btn-search"><i class="fa fa-search"></i>查询</button>
                </div>
            </div>
        </div><!-- /.page-header -->

        <table class="table table-striped table-bordered table-hover ltable">
            <thead>
                <tr>
                    <th width="8%">选择</th>
                    <th align="left">数据类别</th>
                    <th align="left">项目代码</th>
                    <th align="left">项目名称</th>
                    <th width="8%">操作</th>
                </tr>
            </thead>
            <tbody id="page_list"></tbody>
        </table>
        <div id="pagination" class="default"></div>
    </div>
</div>
@section includeJs{
    <script src="~/ad_min/js/jq/jquery.pagination.js"></script>
    <script type="text/javascript">
    var $pgConfig = {
        pgList: '#page_list',
        pgDiv: '#pagination',
        pageSize: '10',
        currPage: '0',
        param:{
            keyword: '@ViewBag.keyword'
        },
        sendUrl: '@Url.Action("DictBase_Bind", "Settings", new { Area = "ad_min" })'
    };
    function getParam()
    {
        var params = "&keyword=" + $pgConfig.param.keyword;
        return params;
    }
    $(function () {
        //搜索事件
        $("#btnSearch").click(function () {
            var keyword = $(".keyword").val();
            $pgConfig.param.keyword = keyword;
            AjaxPgList(0);
        });
        //初始化列表
        AjaxPgList(0);

        //删除
        $("#btnDelete").click(function () {
            var ids = chkVal("chkId");
            $confirm("您确定要删除吗？", function () {
                $.ajaxPostJson("@Url.Action("DictBase_Del", "Settings", new { Area = "ad_min" })", { ids: ids }, function (result) {
                    var url = "dictbase_list";
                    delAlert(result.message, url);
                }, function () {
                    var url = "dictbase_list";
                    delAlert("删除失败或权限不够！", url);
                }
                , function (XMLHttpRequest) {//beforeSend
                    $("#btnDelete").attr("disabled", true);
                });
            })
        });

    });

    /*分页*/
    function AjaxPgList(currPage) {
        $.ajax({
            type: "post",
            dataType: "json",
            url: $pgConfig.sendUrl + "?page_size=" + $pgConfig.pageSize + "&page_index=" + currPage+getParam(),
            beforeSend: function (XMLHttpRequest) {
                $($pgConfig.pgDiv).html('<div style="line-height:35px;width:100%">正在很努力加载，请稍候...</div>');
            },
            success: function (data) {
                var strHtml = '';
                var row = data.rows;
                for (var i in row) {
                    strHtml += '<tr>'
                    + '<td class="center"><label class="checkall"><input name="chkId" type="checkbox" class="ace" value="' + row[i].id + '" /><span class="lbl"></span></label></td>'
                    + '<td><a href="dictbase_edit?act=Edit&id=' + row[i].id + '">' + row[i].Key_Type + '</a></td>'
                    + '<td>' + row[i].Key_Code + '</td>'
                    + '<td>' + row[i].Key_Value + '</td>'
                    + '<td align="center"><a href="dictbase_edit?act=Edit&id=' + row[i].id + '">修改</a></td>'
                    + '</tr>';
                }
                $($pgConfig.pgList).html(strHtml);
                pageCount = data.total;
                $($pgConfig.pgDiv).pagination(pageCount, {
                    callback: pageselectCallback,
                    prev_text: "« 上一页",
                    next_text: "下一页 »",
                    items_per_page: $pgConfig.pageSize,
                    num_display_entries: 5,//展示多少页后使用省略号
                    current_page: currPage,
                    num_edge_entries: 2,//省略号后显示多少页
                    link_to: "javascript:;"
                });
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                $($pgConfig.pgDiv).html('<div style="line-height:35px;width:100%">暂无数据</div>');
            }
        });
    }
    //分页点击事件
    function pageselectCallback(page_id) {
        AjaxPgList(page_id)
    }
    </script>
}