APP/NC.MVC/Areas/ad_min/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;

using Microsoft.AspNetCore.Mvc;
using NC.Common;
using NC.Core;
using NC.Lib;
using NC.Model;
using NC.Model.Models;

namespace NC.MVC.Areas.ad_min.Controllers
{
    /// <summary>
    /// 管理
    /// </summary>
    [Area(AreaNames.Admin)]
    public class ManagerController : AdminBase
    {

        public ManagerController(NCMVC_DBContext _dblEf) : base(_dblEf)
        {
        }
        public ManagerController()
        {
        }

        private string action = JHEnums.ActionEnum.Add.ToString(); //操作类型

        protected string strStatus = string.Empty;
        protected string strMsg = string.Empty;

        #region--菜单处理--

        /// <summary>
        /// 菜单列表
        /// </summary>
        [NavAttr(NavName = "sys_nav")]
        public ActionResult Nav_List()
        {
            //获得列表
            ViewBag.AllNav = "";
            return View();
        }
        /// <summary>
        /// 菜单列表-编辑
        /// </summary>
        [NavAttr(NavName = "sys_nav")]
        public ActionResult Nav_Edit()
        {
            action = Request.Query["act"];
            int id = Utils.StrToInt(Request.Query["id"]);
            NcNavigation model = new NcNavigation();
            if (action.ToLower() == JHEnums.ActionEnum.Edit.ToString().ToLower() && id != 0) //修改
            {
                model = BindNav(id);
            }
            else
            {
                model.SortId = 99;
                if (id != 0)
                {
                    model.ParentId = id;
                }
            }
            ViewBag.action = action;
            ViewBag.id = id;
            return View(model);
        }
        /// <summary>
        /// 绑定菜单
        /// </summary>
        private NcNavigation BindNav(int id)
        {
            NcNavigation model = dblEf.Find<NcNavigation>(id);
            return model;
        }
        /// <summary>
        /// 验证菜单是否包含
        /// </summary>
        [NavAttr(NavName = "sys_nav")]
        public JsonResult nav_validate()
        {
            string navname = Request.Form["param"].ToString();
            string old_name = Request.Query["old_name"].ToString();

            string strStatus = "y";
            string strMsg = "该导航菜单ID可使用！";
            if (string.IsNullOrEmpty(navname))
            {
                strStatus = "n";
                strMsg = "该导航菜单ID不可为空！";
            }
            else if (navname.ToLower() == old_name.ToLower())//未改
            {
                //strMsg = "该导航菜单ID可使用！";
            }
            //检查保留的名称开头
            else if (navname.ToLower().StartsWith("channel_"))
            {
                strStatus = "n";
                strMsg = "该导航菜单ID系统保留，请更换！";
            }
            else
            {
                NcNavigation model = dblEf.NcNavigation.Where(n => n.Name == navname).FirstOrDefault();
                if (model != null)
                {
                    strStatus = "n";
                    strMsg = "该导航菜单ID已被占用，请更换！";
                }
            }
            return Json(new { status = strStatus, info = strMsg });
        }

        /// <summary>
        /// 保存导航菜单
        /// </summary>
        /// <param name="model"></param>
        [NavAttr(NavName = "sys_nav")]
        public JsonResult NavSave()
        {
            NcNavigation model = new NcNavigation();
            action = Request.Form["act"];
            if (action.ToLower() == JHEnums.ActionEnum.Edit.ToString().ToLower())//修改
            {
                int id = Utils.StrToInt(Request.Form["id"]);
                model = dblEf.Find<NcNavigation>(id);
                model = NavSetModel(model);

                if (NavUpdate(model))
                {
                    CacheHelper.Remove("NC_nav");
                    strStatus = "1";
                    strMsg = "保存成功";
                }
            }
            else//新增
            {
                model = NavSetModel(model);

                model.ChannelId = 0;
                model.IsSys = 0;
                if (NavAdd(model) > 0)
                {
                    CacheHelper.Remove("NC_nav");
                    strStatus = "1";
                    strMsg = "保存成功";
                }
            }
            return Json(new { status = strStatus, msg = strMsg });
        }

        private NcNavigation NavSetModel(NcNavigation model)
        {
            model.NavType = JHEnums.NavigationEnum.System.ToString();
            model.Name = Request.Form["txtName"];
            model.Title = Request.Form["txtTitle"];
            model.SubTitle = Request.Form["txtSubTitle"];
            model.LinkUrl = Request.Form["txtLinkUrl"];
            model.SortId = Utils.StrToInt(Request.Form["SortId"]);
            model.IsLock = 0;
            if (Request.Form["is_lock"] == "on")
            {
                model.IsLock = 1;
            }
            model.Remark = Request.Form["remark"];
            int parentId = Utils.StrToInt(Request.Form["parent_id"]);
            //如果选择的父ID不是自己,则更改
            if (parentId != model.Id || model.Id == 0)
            {
                model.ParentId = parentId;
            }

            //添加操作权限类型
            model.ActionType = Request.Form["cblActionType"];

            return model;
        }
        /// <summary>
        /// 增加一条数据
        /// </summary>
        [HttpPost]
        public int NavAdd(NcNavigation model)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("insert into nc_Navigation(");
            strSql.Append("nav_type,name,title,sub_title,link_url,Sort_Id,is_lock,remark,Parent_Id,channel_id,action_type,is_sys)");
            strSql.Append(" values (");
            strSql.Append("@nav_type,@name,@title,@sub_title,@link_url,@SortId,@is_lock,@remark,@ParentId,@channel_id,@action_type,@is_sys)");
            strSql.Append(";select @ReturnValue= @@IDENTITY ");
            strSql.Append(@"if @@error<>0 begin rollback tran
                                    select N'fail' as result
                                    return
                                end");
            string sql = @"                
                            Begin Tran
                                declare @ReturnValue as int
                                " + strSql.ToString() + @"
                                select N'success' as result
                            Commit Tran
                        ";

            DbParameters p = new DbParameters();
            p.Add("@ParentId", model.ParentId);
            p.Add("@channel_id", model.ChannelId);
            p.Add("@action_type", model.ActionType);
            p.Add("@is_sys", model.IsSys);
            p.Add("@nav_type", model.NavType);
            p.Add("@name", model.Name);
            p.Add("@title", model.Title);
            p.Add("@sub_title", model.SubTitle);
            p.Add("@link_url", model.LinkUrl);
            p.Add("@SortId", model.SortId);
            p.Add("@is_lock", model.IsLock);
            p.Add("@remark", model.Remark);
            string result = Utils.ObjectToStr(Dbl.ZZCMS.CreateSqlScalar(sql, p));
            return result == "success" ? 1 : 0;
        }
        /// <summary>
        /// 更新一条数据
        /// </summary>

        [HttpPost]
        public bool NavUpdate(NcNavigation model)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("update nc_Navigation set ");
            strSql.Append("nav_type=@nav_type,");
            strSql.Append("name=@name,");
            strSql.Append("title=@title,");
            strSql.Append("sub_title=@sub_title,");
            strSql.Append("link_url=@link_url,");
            strSql.Append("Sort_Id=@SortId,");
            strSql.Append("is_lock=@is_lock,");
            strSql.Append("remark=@remark,");
            strSql.Append("Parent_Id=@ParentId,");
            strSql.Append("channel_id=@channel_id,");
            strSql.Append("action_type=@action_type,");
            strSql.Append("is_sys=@is_sys");
            strSql.Append(" where id=@id;");
            strSql.Append(@"if @@error<>0 begin rollback tran
                                    select N'fail' as result
                                    return
                                end");
            //
            StringBuilder strChild = new StringBuilder();
            StringBuilder strN = new StringBuilder();
            //string sC = UpdateChilds(strChild, model.ParentId);
            //string sn = UpdateChilds(strN, model.id);
            //先判断选中的父节点是否被包含
            //查找旧父节点数据
            //" + sC + @"
            //" + sn + @"
            string sql = @"                
                            Begin Tran
                                declare @ReturnValue as int
                                " + strSql.ToString() + @"
                                select N'success' as result
                            Commit Tran
                        ";

            DbParameters p = new DbParameters();
            p.Add("@id", model.Id);
            p.Add("@ParentId", model.ParentId);
            p.Add("@channel_id", model.ChannelId);
            p.Add("@action_type", model.ActionType);
            p.Add("@is_sys", model.IsSys);
            p.Add("@nav_type", model.NavType);
            p.Add("@name", model.Name);
            p.Add("@title", model.Title);
            p.Add("@sub_title", model.SubTitle);
            p.Add("@link_url", model.LinkUrl);
            p.Add("@SortId", model.SortId);
            p.Add("@is_lock", model.IsLock);
            p.Add("@remark", model.Remark);

            string result = Utils.ObjectToStr(Dbl.ZZCMS.CreateSqlScalar(sql, p));
            return result == "success";
        }

        /// <summary>
        /// 删除菜单
        /// </summary>
        [NavAttr(NavName = "sys_nav")]
        public ActionResult DelNav(string ids)
        {

APP/NC.MVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using NC.Lib;

namespace NC.MVC.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 用户登录
        /// </summary>
        /// <param name="userName">用户ID</param>
        /// <param name="passWord">用户密码</param>
        /// <param name="rememberMe">是否记住密码</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Login(string userName, string passWord, string rememberMe, string txtCode)
        {
            var user = new ClaimsPrincipal(
             new ClaimsIdentity(new[]
             {
                        new Claim("UserName","UserNameValue"),
                        new Claim("UserPwd","UserPwdValue"),
             }, UserAuthorizeAttribute.UserAuthenticationScheme)
            );
            HttpContext.SignInAsync(UserAuthorizeAttribute.UserAuthenticationScheme, user, new AuthenticationProperties
            {
                ExpiresUtc = DateTime.UtcNow.AddMinutes(60),// 有效时间
                //ExpiresUtc = DateTimeOffset.Now.Add(TimeSpan.FromDays(7)), // 有效时间
                IsPersistent = true,
                AllowRefresh = false
            });
            return new RedirectResult("~/Home/Index");//登录成功
        }
    }
}

APP/NC.MVC/Areas/ad_min/Views/Shared/_Footer.cshtml
<div class="footer" style="text-align:center">
    2016 &copy; wyd by 604401109@qq.com
</div>

APP/NC.MVC/Areas/ad_min/Views/Shared/_Header.cshtml
@*<div class="navbar navbar-default" id="navbar" style="display:block;">
    <script type="text/javascript">
        try { ace.settings.check('navbar', 'fixed') } catch (e) { }
    </script>

    <div class="navbar-container" id="navbar-container">
        <div class="navbar-header pull-left">
            <a href="#" class="navbar-brand">
                <small>
                    <i class="fa fa-leaf"></i>
                    @(new ManageController().siteConf.webname)
                </small>
            </a><!-- /.brand -->
        </div><!-- /.navbar-header -->
        @{
            //NC.Model.manager adminInfo = new NC.Model.manager();
            ////adminInfo= new ManageController().GetAdminInfo(); //管理员信息
            NC.Model.manager adminInfo = new NC.Model.manager();
            if (Session["admin_info"]!=null) { adminInfo = Session["admin_info"] as NC.Model.manager; }
        }
        <div class="navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="light-blue">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <span class="user-info" style="padding-top:10%;">
                            @(adminInfo == null ? "" : adminInfo.user_name),您好！
                            <i class="fa fa-caret-down"></i>
                        </span>
                    </a>
                    <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="@Url.Action("sys_config", "settings", new { Area = "ad_min" })">
                                <i class="fa fa-cog"></i>
                                系统参数设置
                            </a>
                        </li>
                        <li>
                            <a href="javascript:dialog('@Url.Action("manager_edit", "Manager", new { Area = "ad_min" })?act=Edit&id=@adminInfo.id&dept_id=0')">
                                <i class="fa fa-user"></i>
                                个人资料
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("LoginOut", "Login", new { Area = "ad_min" })">
                                <i class="fa fa-off"></i>
                                退出
                            </a>
                        </li>
                    </ul>
                </li>
            </ul><!-- /.ace-nav -->
        </div><!-- /.navbar-header -->
    </div><!-- /.container -->
</div>
<script type="text/javascript">
    function dialog(url) {
        lhgShowDialog("用户管理", url, document.body.clientWidth - (document.body.clientWidth * 0.2), document.body.scrollHeight - (document.body.scrollHeight * 0.2));
    }
</script>*@

APP/NC.MVC/Areas/ad_min/Views/Shared/_Layout.Edit.cshtml
@using System.Data;
@using NC.Common;
@using NC.Core;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <link rel="shortcut icon" href="favicon.ico">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/skin/animsition.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/animate.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/layout.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/js/artdialog/ui-dialog.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/ad_min/cms_os/site.css" asp-append-version="true"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/skin/animsition.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/animate.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/layout.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/js/artdialog/ui-dialog.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/cms_os/site.css" asp-append-version="true" />
    </environment>
    <!--[if lt IE 8]>
    <meta http-equiv="refresh" content="0;url=ie.html" />
    <![endif]-->
    @RenderSection("includecss", required: false)
</head>
<body class="gray-bg">
    <!-- 页面内容 -->
    @RenderBody()
    <!-- /页面内容 -->
    <!-- 全局js -->
    <script src="~/ad_min/js/jquery.min.js?v=2.1.4"></script>
    <script src="~/ad_min/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="~/ad_min/js/plugins/layer/layer.min.js"></script>
    <script type="text/javascript" src="~/ad_min/js/artdialog/dialog-plus-min.js"></script>
    <script src="~/ad_min/js/Validform/Validform_v5.3.2.js"></script>
    <script src="~/ad_min/cms_os/cms_main.js"></script>
    <!--页面自定义js-->
    @RenderSection("includeJs", required: false)
    <!--/页面自定义js-->
</body>
<!-- END BODY -->
</html>

APP/NC.MVC/Areas/ad_min/Views/Shared/_Layout.cshtml
@using System.Data;
@using NC.Common;
@using NC.Core;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <link rel="shortcut icon" href="favicon.ico">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" asp-append-version="true" />
        <link href="~/ad_min/skin/icon/iconfont.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/ad_min/skin/animsition.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/animate.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/layout.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/skin/nav.css?v=1.0.0" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/js/artdialog/ui-dialog.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/cms_os/site.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" asp-append-version="true" />
        <link href="~/ad_min/skin/icon/iconfont.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/ad_min/skin/animsition.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/animate.css" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/skin/layout.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/skin/nav.css?v=1.0.0" asp-append-version="true">
        <link rel="stylesheet" href="~/ad_min/js/artdialog/ui-dialog.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ad_min/cms_os/site.css" asp-append-version="true" />
    </environment>
    <!--[if lt IE 8]>
    <meta http-equiv="refresh" content="0;url=ie.html" />
    <![endif]-->
    @RenderSection("includecss", required: false)
</head>
<body class="gray-bg">
    <!-- 页面内容 -->
    @RenderBody()
    <!-- /页面内容 -->
    <!-- 全局js -->
    <script src="~/ad_min/js/jquery.min.js?v=2.1.4"></script>
    <script src="~/ad_min/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="~/ad_min/js/plugins/layer/layer.min.js"></script>
    <script type="text/javascript" src="~/ad_min/js/artdialog/dialog-plus-min.js"></script>
    <script src="~/ad_min/cms_os/cms_main.js"></script>
    <!--页面自定义js-->
    @RenderSection("includeJs", required: false)
    <!--/页面自定义js-->
</body>
<!-- END BODY -->
</html>

APP/NC.MVC/Areas/ad_min/Views/Shared/_Menu.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="nav-close">
        <i class="fa fa-times-circle"></i>
    </div>
    <div class="sidebar-collapse side-menu" id="side-menu">

        <div class="side-menu-group active">
            <h1 title="站点" main-nav-icon="fa fa-home"><i class="fa fa-home"></i></h1>
            <div class="side-menu-wrap">
                <h2><i class="fa fa-home"></i><span>默认站点</span><b class="fa fa-angle-double-down"></b></h2>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>新闻资讯 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="list.html" id="1"><i class="fa fa-table"></i>内容管理</a></li>
                            <li><a class="J_menuItem" href="category.aspx?channel=1"><i class="fa fa-table"></i>栏目类别</a></li>
                            <li><a class="J_menuItem" href="comment.aspx?channel=1"><i class="fa fa-table"></i>评论管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>购物商场 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="article.aspx?channel=2"><i class="fa fa-table"></i>内容管理</a></li>
                            <li><a class="J_menuItem" href="category.aspx?channel=2"><i class="fa fa-table"></i>栏目类别</a></li>
                            <li><a class="J_menuItem" href="comment.aspx?channel=2"><i class="fa fa-table"></i>评论管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>视频专区 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="article.aspx?channel=2"><i class="fa fa-table"></i>内容管理</a></li>
                            <li><a class="J_menuItem" href="category.aspx?channel=2"><i class="fa fa-table"></i>栏目类别</a></li>
                            <li><a class="J_menuItem" href="comment.aspx?channel=2"><i class="fa fa-table"></i>评论管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>图片分享 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="article.aspx?channel=2"><i class="fa fa-table"></i>内容管理</a></li>
                            <li><a class="J_menuItem" href="category.aspx?channel=2"><i class="fa fa-table"></i>栏目类别</a></li>
                            <li><a class="J_menuItem" href="comment.aspx?channel=2"><i class="fa fa-table"></i>评论管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>资源下载 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="article.aspx?channel=2"><i class="fa fa-table"></i>内容管理</a></li>
                            <li><a class="J_menuItem" href="category.aspx?channel=2"><i class="fa fa-table"></i>栏目类别</a></li>
                            <li><a class="J_menuItem" href="comment.aspx?channel=2"><i class="fa fa-table"></i>评论管理</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>公司介绍 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="article.aspx?channel=2"><i class="fa fa-table"></i>内容管理</a></li>
                            <li><a class="J_menuItem" href="category.aspx?channel=2"><i class="fa fa-table"></i>栏目类别</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="side-menu-group">
            <h1 title="会员" main-nav-icon="fa fa-group"><i class="fa fa-group"></i></h1>
            <div class="side-menu-wrap">
                <h2><i class="fa fa-group"></i> <span>会员管理</span><b class="fa fa-angle-double-down"></b></h2>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>会员管理 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>审核会员</a></li>
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>会员列表</a></li>
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>会员组别</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>会员日志 <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>站内短消息</a></li>
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>充值记录</a></li>
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>消费记录</a></li>
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>积分记录</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bars"></i>会员设置  <b class="fa arrow"></b></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href=""><i class="fa fa-edit"></i>参数设置</a></li>
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>OAuth设置</a></li>
                            <li><a class="J_menuItem" href=""><i class="fa fa-table"></i>邮件模板</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

    </div>
</nav>